Feature/#90 pwa
smartive-education/app-pizza-hawaii pull request #101
Opened 2023-04-13 16:01 UTC by flxtagi

![Screenshot 2023-04-13 at 16 25 35](https://user-images.githubusercontent.com/15230747/231817913-a7068382-5724-49f8-9318-5a2b7dba2e36.jpg)

looks neat! 😄 
works only with the last next js version

2023-04-13 18:00 UTC, rudigier commented
![Bildschirmfoto 2023-04-13 um 20 00 04](https://user-images.githubusercontent.com/3023646/231845083-43584c72-4ab5-479e-bb4e-3062a1e49823.png)

2023-04-13 18:01 UTC, rudigier requested changes

2023-04-13 18:01 UTC, rudigier commented on package.json
Are there other impacts when change the next version?

2023-04-13 18:11 UTC, rudigier commented
offline nothing get's displayed. Or do i something wrong?
![Uploading Bildschirmfoto 2023-04-13 um 20.10.29.png…]()

2023-04-13 18:13 UTC, rudigier commented
![Bildschirmfoto 2023-04-13 um 20 13 31](https://user-images.githubusercontent.com/3023646/231847695-b3d5a1d9-49c2-4a61-b284-389467af1c37.png)

2023-04-13 21:00 UTC, flxtagi commented on package.json
lets check that by merging master and develop branch into it

2023-04-14 12:58 UTC, flxtagi commented on public/sw.js
removed

2023-04-14 12:58 UTC, flxtagi commented on src/pages/_app.tsx
we should move assets to /assets folder. best practice

2023-04-14 15:12 UTC, flxtagi commented
works now with next v.13.2.4
plaease check in on vercel on mobile

2023-04-14 21:19 UTC, rudigier approved these changes

2023-04-14 21:19 UTC, rudigier commented on src/pages/_app.tsx
Created a ticket https://github.com/smartive-education/app-pizza-hawaii/issues/105

2023-04-15 18:03 UTC, merged