Feature/#54 fixes errors
smartive-education/app-pizza-hawaii pull request #107
Opened 2023-04-16 20:04 UTC by flxtagi

your fixes included (branch #95 Refactor)

fixes for: 
- undefined lenght when comming back from a client-rendered site. 
- manifest. 
- some libraries updated. should fix deprecation warining
- favicon fix
- no /static all /public folder
- hydration error while skeleton loading for posts
- postList fixes if undefined. 

TBD: discuss if this router.replace is a good enough solution

2023-04-16 21:39 UTC, rudigier requested changes

2023-04-16 21:39 UTC, rudigier commented on src/components/post/PostList.tsx
Please revert changes. Use instead Math.rand -> i % 2

2023-04-16 21:39 UTC, rudigier commented on src/components/helpers/PostSkeleton.tsx
please revert changes

2023-04-16 21:39 UTC, rudigier commented on src/pages/_app.tsx
please remove /public/

2023-04-16 21:39 UTC, rudigier commented on src/pages/index.tsx
> +	const canLoadMore = postCount > posts?.length || false;
please revert this line

2023-04-16 21:54 UTC, flxtagi commented on src/pages/index.tsx
> +	const canLoadMore = postCount > posts?.length || false;
changed

2023-04-17 18:33 UTC, rudigier approved these changes
ok for me

2023-04-17 18:34 UTC, merged