Feature/#74 Eslint rules
smartive-education/app-pizza-hawaii pull request #91
Opened 2023-04-07 12:52 UTC by flxtagi

Es Lint rules
no consoles (warn)
import sorting (warn)
react hooks (warn)
fixed all imports on that branch

2023-04-07 15:15 UTC, rudigier requested changes

2023-04-07 15:15 UTC, rudigier commented on src/services/qwacker.ts
Please do not remove this at the moment - needed for debugging. When we have all the pages ready we can remove this.

2023-04-08 20:03 UTC, flxtagi commented on src/services/qwacker.ts
of course. I thought so.. its counter is back in.

2023-04-11 16:10 UTC, rudigier approved these changes

2023-04-11 16:10 UTC, merged