Feature/#85 Errorhandling
smartive-education/app-pizza-hawaii pull request #93
Opened 2023-04-11 13:52 UTC by flxtagi

lets test with this configuration. not tested all Errors.

2023-04-11 19:40 UTC, flxtagi commented
catch really 500 errors ? 
static getDerivedStateFromError(error: unknown) {

500 Qwacker API request failed with status 500 (Internal Server Error).

2023-04-16 21:42 UTC, rudigier requested changes

2023-04-16 21:42 UTC, rudigier commented on src/pages/index.tsx
Guess throw a error would be better that show this Custom500

2023-04-19 16:30 UTC, flxtagi commented on src/pages/index.tsx
> +		return <Custom500Page errorInfo={error} />;
lets test that if error page needs here

2023-04-19 20:38 UTC, rudigier approved these changes
Thanks for the changes. Looks good. Let's see how vercel likes it.

2023-04-19 20:38 UTC, merged