Feature/#65 dependency cruiser
smartive-education/app-pizza-hawaii pull request #98
Opened 2023-04-12 15:16 UTC by flxtagi

good news: dep cruiser runs through. 
middle good news: I had to add a pseudo object for post to satisfy the dep cruiser. 
I did a good comment why this has been done. 

I think when you are finished with the image component maybe we can simplify the component again and just pass the image-related data to the component ImageModal.

2023-04-13 06:27 UTC, rudigier requested changes

2023-04-13 06:27 UTC, rudigier commented on src/components/ProfileHeader.tsx
I would say it's not the way we should go. 
We have a Image, create a Post of this Image to show just the image? We should update the ImageModal

2023-04-14 15:29 UTC, flxtagi commented on src/components/ProfileHeader.tsx
1. changed Imagemodal data image model for and did a cleaner refactoring. 
2. there is now only  src/components/form/AccountForm.tsx which has no-orphans. this is not used at the moment right?
3. added all the api pages to the exception with comment.

2023-04-14 21:27 UTC, rudigier approved these changes

2023-04-14 21:27 UTC, rudigier commented on src/components/ProfileHeader.tsx
correct. Thank you!

2023-04-14 22:16 UTC, merged